# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fjira < Formula
  desc ""
  homepage "https://github.com/mk-5/fjira"
  version "0.11.3"
  license "AGPL-3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mk-5/fjira/releases/download/0.11.3/fjira_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "d49e3937f1b9b7deda1286c977b3dc126c05e095776df14b3d2bcb06746aa798"

      def install
        bin.install "fjira"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mk-5/fjira/releases/download/0.11.3/fjira_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "2da895867b5d918c0a8b484c92ea9bcc685d5ecba3d9f6c255afd2f96e4661a0"

      def install
        bin.install "fjira"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/mk-5/fjira/releases/download/0.11.3/fjira_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "a58b52d8406d6efc2ac4f8e280141aae26aa81327631bf3914c8bcb8ca4724b1"

      def install
        bin.install "fjira"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mk-5/fjira/releases/download/0.11.3/fjira_Linux_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "78426d84f8cbef3bd54e32401e919a67ac452b72afec180dad1300e9c8ed1d5b"

      def install
        bin.install "fjira"
      end
    end
  end
end
