# This file was generated by GoReleaser. DO NOT EDIT.
cask "fjira" do
  name "fjira"
  desc ""
  homepage "https://github.com/mk-5/fjira"
  version "1.4.7"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fjira"

  on_macos do
    on_intel do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Darwin_x86_64.tar.gz"
      sha256 "620cde5919f156fdf1d1c2d57f98fb827f5ad5acf3a3318ac468a3230e23b9f2"
    end
    on_arm do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Darwin_arm64.tar.gz"
      sha256 "c97ead965a5c5a69fb129017414f1816b1299b559ad16c8a9ec00cf4bf40765c"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Linux_x86_64.tar.gz"
      sha256 "893d7e75bcff48bb59e585f76b649883e7e96176e86fa314dfb90336f5a75ed1"
    end
    on_arm do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Linux_arm64.tar.gz"
      sha256 "4bae3bbd5b10d09256de142e551c41fd5d7d5a3723f965b2774b123f2104ea07"
    end
  end

  # No zap stanza required
end
