# This file was generated by GoReleaser. DO NOT EDIT.
cask "fjira" do
  name "fjira"
  desc ""
  homepage "https://github.com/mk-5/fjira"
  version "1.4.8"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fjira"

  on_macos do
    on_intel do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Darwin_x86_64.tar.gz"
      sha256 "29d9de637e5a83cca820cdc595e82f196f3416fa9d2ff62c76033e0d4e0f4695"
    end
    on_arm do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Darwin_arm64.tar.gz"
      sha256 "a24d48081ff950eb065fa12a3bb6368028890cb243fdf51008d6858dfb73e542"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Linux_x86_64.tar.gz"
      sha256 "afeb7339b53475396c69b2ef9baabd78ac4b3693eee11c2da4ec74d728148da6"
    end
    on_arm do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Linux_arm64.tar.gz"
      sha256 "06d964283be40d7ded1d6e80e85b9a760926d45a136c04e649ec15d3d1e3033e"
    end
  end

  # No zap stanza required
end
