# This file was generated by GoReleaser. DO NOT EDIT.
cask "fjira" do
  name "fjira"
  desc ""
  homepage "https://github.com/mk-5/fjira"
  version "1.4.9"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "fjira"

  on_macos do
    on_intel do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Darwin_x86_64.tar.gz"
      sha256 "4775bbe17e7f588ed34050350973e4073be7c920d1f6e00e9c0c2fe81fb7a705"
    end
    on_arm do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Darwin_arm64.tar.gz"
      sha256 "9a59d09ba6066c8a77436d8affff76ba6504eaa1d8c2740b79e09e4db4c4fbc1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Linux_x86_64.tar.gz"
      sha256 "470d96b0a25a77f126abc0a3241df01aaa12ff932a50398c18afecb8be0e5bed"
    end
    on_arm do
      url "https://github.com/mk-5/fjira/releases/download/#{version}/fjira_Linux_arm64.tar.gz"
      sha256 "c4daae6b5f7a2e4b66ce5087292c6753a2ed7f86383f95887b78b98a3b4f367e"
    end
  end

  # No zap stanza required
end
